name: Option ML Auto Tracker

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 mins
  workflow_dispatch:

jobs:
  run-predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install tensorflow gdown joblib requests scikit-learn

    - name: Run prediction
      run: python option_ml_tracker.py

    - name: Commit and push results
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add live_signals.csv
        git commit -m "Update live ML signals"
        git push
