name: Run Option ML Signal Every 5 Min

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system & Python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libxslt-dev python3-dev
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Option ML Predictor
      run: |
        python option_ml_tracker.py

    - name: Commit new Parquet output
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add combined_data.parquet
        git commit -m "Update: New ML signals" || echo "No changes"
        git push
